import type {
  AdminUser,
  StaffMember,
  StaffInvitation,
  EmployeeApplication,
  SecuritySession,
  AuditActivity,
} from "@/types/admin";
import { allPermissions } from "@/lib/admin/config";
export const currentAdminUser: AdminUser = {
  id: "owner",
  fullName: "Alex Morgan",
  displayName: "Alex",
  email: "alex@ascend.demo",
  role: "SUPER_ADMIN",
  permissions: allPermissions,
};
export const staff: StaffMember[] = [
  {
    id: "s1",
    fullName: "Olivia Chen",
    displayName: "Olivia",
    email: "olivia@ascend.demo",
    role: "STAFF",
    permissions: allPermissions,
    status: "ACTIVE",
    lastLogin: "2026-10-05T08:42:00Z",
    ip: "203.0.113.24",
  },
  {
    id: "s2",
    fullName: "Marcus Reed",
    displayName: "Marcus",
    email: "marcus@ascend.demo",
    role: "STAFF",
    permissions: allPermissions.slice(0, 2),
    status: "ACTIVE",
    lastLogin: "2026-10-05T07:15:00Z",
    ip: "203.0.113.81",
  },
  {
    id: "s3",
    fullName: "Sofia Laurent",
    displayName: "Sofia",
    email: "sofia@ascend.demo",
    role: "STAFF",
    permissions: [allPermissions[0], "order.view", "chat.view"],
    status: "ACTIVE",
    lastLogin: "2026-10-04T19:30:00Z",
    ip: "198.51.100.12",
  },
  {
    id: "s4",
    fullName: "James Park",
    displayName: "James",
    email: "james@ascend.demo",
    role: "STAFF",
    permissions: [],
    status: "SUSPENDED",
    lastLogin: "2026-10-02T11:20:00Z",
    ip: "198.51.100.46",
  },
];
export const invitations: StaffInvitation[] = [
  {
    id: "inv-101",
    email: "nina@ascend.demo",
    fullName: "Nina Williams",
    displayName: "Nina",
    permissions: allPermissions,
    status: "PENDING",
    createdAt: "2026-10-05T08:20:00Z",
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    token: "demo-invitation",
  },
  {
    id: "inv-102",
    email: "ethan@ascend.demo",
    fullName: "Ethan Brooks",
    displayName: "Ethan",
    permissions: [allPermissions[0]],
    status: "PENDING",
    createdAt: "2026-10-05T07:00:00Z",
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: "inv-103",
    email: "olivia@ascend.demo",
    fullName: "Olivia Chen",
    displayName: "Olivia",
    permissions: allPermissions,
    status: "ACCEPTED",
    createdAt: "2026-10-01T09:00:00Z",
    expiresAt: "2026-10-02T09:00:00Z",
  },
  {
    id: "inv-104",
    email: "ryan@ascend.demo",
    fullName: "Ryan Scott",
    displayName: "Ryan",
    permissions: [],
    status: "EXPIRED",
    createdAt: "2026-10-01T09:00:00Z",
    expiresAt: "2026-10-02T09:00:00Z",
  },
  {
    id: "inv-105",
    email: "mia@ascend.demo",
    fullName: "Mia Jones",
    displayName: "Mia",
    permissions: [],
    status: "REVOKED",
    createdAt: "2026-09-30T09:00:00Z",
    expiresAt: "2026-10-01T09:00:00Z",
  },
];
const candidates = [
  [
    "app-1048",
    "Daniel Nguyen",
    "Nova",
    "BOOSTER",
    "Nova#VN2",
    "Challenger",
    "PENDING",
  ],
  [
    "app-1047",
    "Isabella Torres",
    "Luna",
    "COACH",
    "Luna#EUW",
    "Grandmaster",
    "PENDING",
  ],
  [
    "app-1046",
    "Oliver Kim",
    "Zero",
    "BOOSTER",
    "Zero#KR1",
    "Master",
    "PENDING",
  ],
  [
    "app-1045",
    "Emma Wilson",
    "Ember",
    "COACH",
    "Ember#NA1",
    "Challenger",
    "APPROVED",
  ],
  [
    "app-1044",
    "Liam Davis",
    "Ghost",
    "BOOSTER",
    "Ghost#NA2",
    "Diamond",
    "REJECTED",
  ],
  [
    "app-1043",
    "Minh Tran",
    "Aether",
    "BOOSTER",
    "Aether#VN2",
    "Grandmaster",
    "APPROVED",
  ],
] as const;
export const applications: EmployeeApplication[] = candidates.map((c, i) => ({
  id: c[0],
  fullName: c[1],
  displayName: c[2],
  email: `${c[2].toLowerCase()}@example.demo`,
  phone: "+84 912 345 678",
  country: "VN",
  timezone: "Asia/Ho_Chi_Minh",
  positionApplied: c[3],
  riotId: c[4],
  currentRank: c[5],
  status: c[6],
  submittedAt: `2026-10-0${5 - Math.floor(i / 2)}T0${9 - i}:15:00Z`,
  experience:
    "Three years of competitive play and over 200 successful coaching sessions. I specialize in macro strategy, champion fundamentals, and helping players develop lasting improvement habits.",
  note: "Available on weekdays and weekends, 20–30 hours per week. Fluent in English and Vietnamese. Happy to complete a trial session.",
  ...(c[6] !== "PENDING"
    ? { reviewedBy: "Olivia Chen", reviewedAt: "2026-10-04T12:00:00Z" }
    : {}),
  ...(c[6] === "REJECTED"
    ? {
        rejectionReason:
          "Current rank does not meet the requirements for this position.",
      }
    : {}),
  ...(c[6] === "APPROVED"
    ? {
        credentialsSent: true,
        employeeType: c[3],
        department: c[3] === "COACH" ? "COACHING" : "BOOSTING",
        maxActiveOrders: 3,
      }
    : {}),
}));
export const sessions: SecuritySession[] = [
  currentAdminUser,
  ...staff.slice(0, 3),
].map((u, i) => ({
  id: `ses-${i}`,
  userId: u.id,
  user: u.fullName,
  email: u.email,
  role: u.role,
  ip: `203.0.113.${20 + i}`,
  device: i === 2 ? "Safari · macOS" : "Chrome · Windows",
  loginAt: "2026-10-05T07:20:00Z",
  lastActivityAt: "2026-10-05T09:42:00Z",
  status: "ACTIVE",
  current: i === 0,
}));
export const activities: AuditActivity[] = [
  {
    id: "a1",
    action: "STAFF_INVITED",
    description: "Invited Nina Williams to the team",
    actor: "Alex Morgan",
    at: "2026-10-05T08:20:00Z",
  },
  {
    id: "a2",
    action: "EMPLOYEE_APPROVED",
    description: "Approved Emma Wilson’s application",
    actor: "Olivia Chen",
    at: "2026-10-04T12:00:00Z",
  },
  {
    id: "a3",
    action: "PASSWORD_CHANGED",
    description: "Updated account password",
    actor: "Alex Morgan",
    at: "2026-10-04T10:30:00Z",
  },
  {
    id: "a4",
    action: "INVITATION_ACCEPTED",
    description: "Olivia Chen joined the staff team",
    actor: "Olivia Chen",
    at: "2026-10-01T09:30:00Z",
  },
];
